# For more information: https://laravel.com/docs/sail
version: '3'
services:
    curriculumn:
        build:
            context: ./public/docker/8.1
            dockerfile: Dockerfile
            args:
                WWWGROUP: '${WWWGROUP}'
        image: sail-8.0/app
        ports:
            - "8000"
        environment:
            WWWUSER: '${WWWUSER}'
            LARAVEL_SAIL: 1
        volumes:
            - '.:/var/www/html'
        networks:
            - local_net

networks:
    local_net:
        driver: bridge
